import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Upload from "./components/Upload";

import cloudinary from "cloudinary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export type Album = {
  name: string;
  path: string;
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const rootFolders: Album[] = await cloudinary.v2.api.root_folders();
  console.log(rootFolders)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Nav rootFolders={rootFolders} />
        </div>
        <div className="flex w-screen h-screen overflow-scroll justify-center">
          {/* <Home rootFolders={rootFolders} /> */}
          {children}
        </div>
        <div className="absolute right-10 top-10">
          <Upload />
        </div>
      </body>
    </html>
  );
}
