import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Upload from "./components/Upload";
import cloudinary from "cloudinary";
import { SearchResult } from "./page";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export type Album = {
  name: string;
  path: string;
};



export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  const results = (await cloudinary.v2.search
    .expression("resource_type:image")
    .sort_by("uploaded_at", "desc")
    .with_field('tags')
    .max_results(174)
    .execute()) as { resources: SearchResult[] };

    const usage: any = await cloudinary.v2.api.usage().then(result => result);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Nav rootFolders={results} usage={usage}/>
        </div>
        <div className="flex w-screen h-screen overflow-scroll justify-center">
          {/* <Home rootFolders={rootFolders} /> */}
          {children}
        </div>
        <div className="absolute right-10 top-[40px] z-40">
          <Upload />
        </div>
      </body>
    </html>
  );
}
